# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Utils' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Utils
    pod 'Alamofire', '~> 5.4'
    pod 'Nuke', '~> 9.0'
end
